name: Artifactory

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

jobs:
  artifactory:
    name: Artifactory
    runs-on: macos-latest
    concurrency:
      group: ${{ github.ref_name }}
      cancel-in-progress: true
    steps:
    - name: Install dependencies
      run: brew install jfrog-cli
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Archive
      run: tar -czf "Nodes-Tree-Visualizer-${GITHUB_REF_NAME}.tar.gz" Sources
    - name: Upload
      run: >
        jf rt u
        --url="https://tinder.jfrog.io/artifactory"
        --access-token="${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}"
        --flat="true"
        "Nodes-Tree-Visualizer-${GITHUB_REF_NAME}.tar.gz"
        "swift-package-releases/Nodes-Tree-Visualizer/"
