name: DocC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

jobs:
  docc:
    name: DocC
    runs-on: macos-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
    - name: Add ssh key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
        ssh-add - <<< "${{ secrets.TINDER_GITHUB_SSH_KEY }}"
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Build
      run: make docs open="no" DERIVED_DATA_PATH="$(mktemp -d)"
